baseURL = "https://ahmedibrahim.net"
languageCode = "en-us"
title = "Dr Ahmed Ibrahim"
theme = "researcher"

disableKinds = ["taxonomies", "terms", "RSS", "sitemap", "robotsTXT"]
enableEmoji = true

[params]
  author = "Dr Ahmed Ibrahim"
  description = "Official website of Dr Ahmed Ibrahim."
  favicon = "favicon.ico"
  [params.footer]
    text = "Copyright © 2020 Dr Ahmed Ibrahim"
    url = "https://ahmedibrahim.net"

[permalinks]
  "/" = "/:filename"

[menu]
  [[menu.main]]
    name = "About Me"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Contact Details"
    url = "/contact"
    weight = 2

[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files
